apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-promotion-deployment
  namespace: promotion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-promotion
  template:
    metadata:
      labels:
        app: app-promotion
    spec:
      containers:
        - name: app-promotion
          image: promotion:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              valueFrom:
                name: mongo-configmap
                key: database_url
            - name: DB_NAME
              valueFrom:
                name: mongo-configmap
                key: database_name


