apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-promotion-deployment
  namespace: app-promotion
  labels:
    app: app-promotion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-promotion
  template:
    metadata:
      labels:
        app: app-promotion
    spec:
      containers:
        - name: app-promotion
          image: promotion:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          env:
            - name: APP_DEBUG
              key:
                valueFrom:
                  name: app-configmap
                  key: app_debug
            - name: APP_PORT
              valueFrom:
                name: app-configmap
                key: app_port
            - name: MONGO_DB_HOST
              valueFrom:
                name: app-configmap
                key: database_url
            - name: MONGO_DB_NAME
              valueFrom:
                name: app-configmap
                key: database_name
            - name: MONGO_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mongodb_username
            - name: MONGO_DB_PASSWORD
              valueFrom:
                secretRefKey:
                  name: app-secret
                  key: mongodb_password
