apiVersion: v1
kind: Service
metadata:
  name: app-promotion-service
  namespace: app-promotion
spec:
  selector:
    app: app-promotion
  ports:
    - port: 3471
      targetPort: 3471
    - protocol: TCP
      port: 3571
      targetPort: 3571
