apiVersion: v1
kind: Service
metadata:
  name: db-mongo-service
  namespace: db-mongo
spec:
  selector:
    app: db-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
