apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-mongo-deployment
  namespace: db-mongo
  labels:
    app: db-mongo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db-mongo
  template:
    metadata:
      labels:
        app: db-mongo
    spec:
      containers:
        - name: db- mongo
          image: db-mongo
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-mongo-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-mongo-secret
                  key: mongo-root-password
